# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76bf5512ad35b892d63003d7b6d603691cb70278b2c955eed1a1e71d1df03baaf87c0e77f27c1528c92c7490d7e13aa7ed59cce4889c1e2474e08f7d3d4e153

test:
  secret_key_base: a6814af29830f40b44163a883d823cacca270d23114c5b09dec8d55f28adc39d07a4a747a3ca5936bcb5316b3792956a4ce7abc29a9c791fd541aade32fc203b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
